CREATE TABLE `properties` (
  `ID` mediumint(9) NOT NULL AUTO_INCREMENT,
  `APPLICATION` varchar(50) NOT NULL,
  `PROFILE` varchar(50) NOT NULL,
  `LABEL` varchar(50) NOT NULL,
  `KY` varchar(512) NOT NULL,
  `VALUE` varchar(512) NOT NULL,
  `MODIFIED_BY` varchar(30) DEFAULT NULL,
  `MODIFIED_TIME` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;